/*****
    No people table, save info in local storage and for each new letter can change the person
    info if they want. 
******/
CREATE TABLE IF NOT EXISTS letters(
    id bigint generated by default as identity primary key,
    /* Person schema is as follows
        - name: string
        - url?: string
        - stamp_url?: string
     */
    /* currently no way in UI to actually set to_person except manually */
    to_person jsonb,
    from_person jsonb,
    creation_timestamp TIMESTAMP with time zone default timezone('utc'::text, now()) not null,
    /* See LetterContent type */
    letter_content jsonb not null,
    /* This will be a map from color to num_drags */
    interaction_data jsonb,
    should_hide boolean default false not null
);
