CREATE TABLE IF NOT EXISTS letters(
    id bigint generated by default as identity primary key,
    to_person VARCHAR(255),
    from_person VARCHAR(255),
    creation_timestamp TIMESTAMP with time zone default timezone('utc'::text, now()) not null,
    letter_content jsonb not null,
    initial_persistence_data jsonb,
    CONSTRAINT unique_letter UNIQUE (from_person, letter_content)
);

/* 
How to make people unique?
- by display name? 
- by homepage url? (but what if they don't have one?)
- no unique factor?
*/
CREATE TABLE IF NOT EXISTS people(
    id bigint generated by default as identity primary key,
    name VARCHAR(255) not null,
    url VARCHAR(255),
    stamp_url VARCHAR(255),
    stamp bytea,
    CONSTRAINT unique_letter UNIQUE (url)
)
